apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  namespace: mediconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
        - name: patient-service
          image: backend-patient-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          envFrom:
            - secretRef:
                name: jwt-secret
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3003"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: MONGODB_URI_PATIENT
            - name: CONSUL_HOST
              value: consul-service
            - name: CONSUL_PORT
              value: "8500"
            - name: SERVICE_HOST
              value: patient-service
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: mediconnect
spec:
  selector:
    app: patient-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
  type: ClusterIP
